In [20]:
import numpy as np
from sklearn.cluster import KMeans
import matplotlib as plt

In [36]:
x = np.array([
    [1,2],
    [1,4],
    [1,0],
    [10,2],
    [10,4],
    [10,0],
    [45,47],
    [49,50],
    [35,36],
    [30,32]
])

In [37]:
x

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0],
       [45, 47],
       [49, 50],
       [35, 36],
       [30, 32]])

In [38]:
#if n_clusters is not specified, then by default it takes 5 as n_cluster
km = KMeans(n_clusters = 3, random_state = 0)

In [39]:
km.fit(x)

KMeans(n_clusters=3, random_state=0)

In [40]:
km.cluster_centers_

array([[ 5.5,  2. ],
       [32.5, 34. ],
       [47. , 48.5]])

In [41]:
km.predict([
    [0,0],
    [12,4],
    [2,3],
    [37,39],
    [45,47]
    
])

array([0, 0, 0, 1, 2])

In [42]:
km.cluster_centers_

array([[ 5.5,  2. ],
       [32.5, 34. ],
       [47. , 48.5]])

In [43]:
km.predict(x)

array([0, 0, 0, 0, 0, 0, 2, 2, 1, 1])